export const CONTEXT = {
    ACCORDION: 'AccordionContext',
    ACCORDION_ITEM: 'AccordionItemContext',
    FORM: 'FormContext',
    CHECKBOX: 'CheckboxContext',
    SWITCH: 'SwitchContext',
    RADIO: 'RadioContext',
    FOCUS: 'FocusContext',
    COLLAPSIBLE: 'CollapsibleContext',
    POPPER: 'PopperContext',
    POPPERARROW: 'PopperArrowContext',
    MENU: 'MenuContext',
    SUBMENU: 'SubmenuContext',
    MENUINDICATOR: 'MenuIndicatorContext',
    DIALOG: 'DialogContext',
    DISMISSABLE: 'DismissableContext',
    DROPDOWNMENU: 'DropdownMenuContext',
    HOVERCARD: 'HoverCardContext',
    PRORGRESS: 'ProgressContext',
    SCROLL: 'ScrollContext',
    SELECT: 'SelectContext',
    SELECTGROUP: 'SelectGroupContext',
    SELECTITEM: 'SelectItemContext',
    SLIDER: 'SliderContext',
    TOGGLEGROUP: 'ToggleGroupContext',
};