name: Update Google Sitemap

on:
    workflow_run:
        workflows: [Deploy Documentation]
        types:
            - completed
jobs:
    ping:
        name: Ping Google
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'success' }}

        steps:
            - name: Send request
              run: curl http://www.google.com/ping?sitemap=https://sidharth-anand.github.io/teil-ui/sitemap.xml
